language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
- '0.12'
- '0.10'
- node
before_script:
- npm install -g npm
- npm install
script: npm run build
deploy:
  provider: npm
  email: gasiorowski.piotr@gmail.com
  api_key:
    secure: rHrIQqcx5WdsD2xbjhcuAggJ87ZRSexadSCAd2ph7Yibjc27WLL2DZFy+H0ZSIlWhiQH+TkEXffe+iqEGiTfZ3k5N9UWOBJhbST4m2NUaLDAic6AH53orXy6o+XdXRJMEoUIr6Hi849O3OIazXupgcLYt/7/obz9osBOGydCNIMsA6LTYhy36D7k29K6WTCXtMDthXPOaCCZGyd8cO+EGg2mPPi5PBmb6filnIgqXS3fQIigwbNSKxUNOhmnSeDA/RibYYgbqMVneUAR6JimJ+n1ulXItZusceRxGe4rGwFyxSNWYKv0x7TEo4kpYcwlUBte4XFF0kOP57m2ksqAwFnXWzknotro7pMPbG41yAScVmOfE4FA23ah0+oe8AI8gX6Bl1WiqPYz+v1t5Lx+REE+UAW+fNqZYcXzZbIKtuH1H58Jgvi1I5Gq+cI6466f3+h8aoMSdxduBkrpwpIKCeo4uXghJeQJXJkoTY8EfgVZcXnVokOxTdyg7I8LP1uhFk5hyS6XqJM6X3OfcYITk/myGHdZHGHOHBnUEH2RAcRLT+AtFaFlI41ikdS+9WhTBR1K+lwHi3XElioZOpMoBV1Xolw06Mky5XrVnnCrBGtiCxgK8/t2d10jS5/2Dhg4WA9IYAhS8IVP6A66o7VXX1H3q0qAtm4JJZ26PCYSZwk=
  on:
    tags: true
    repo: GasiorowskiPiotr/azure-deploy
